In [1]:
import torch
import numpy as np

# pytorch张量学习

In [2]:
# 判断是否可以使用GPU加速
torch.cuda.is_available()

False

In [3]:
# torch张量
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

### tensor创建与矩阵乘法

In [4]:
eye = torch.eye(3)
eye2 = torch.tensor([[1., 2., 3.], [1., 2., 3.], [1., 2., 3.]])
torch.mm(eye, eye2)

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])

In [5]:
x = torch.linspace(0, 100, 5)
torch.cat((x, x, x), 0)

tensor([  0.,  25.,  50.,  75., 100.,   0.,  25.,  50.,  75., 100.,   0.,  25.,
         50.,  75., 100.])

### numpy数组转换为张量

In [6]:
a = np.array([1, 2, 3])
t = torch.from_numpy(a)
t

tensor([1, 2, 3], dtype=torch.int32)

### 正态分布与tensor的布尔索引

In [7]:
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
x[x > 0]

tensor([0.0579, 1.0999, 0.9866])

### inplace操作
inplace操作是pytorch计算的一种技巧, 它使得pytorch不会创建变量的副本, 而是就地操作，增加了计算效率
inplace操作有两种方式, 一种是加下划线的方法, 一种是类似b += a的操作, 有些令人疑惑, 因为b = b + a就会创建副本

In [8]:
a = torch.ones(1, 3)
b = torch.zeros(1, 3)
b.add(a)
b

tensor([[0., 0., 0.]])

In [9]:
a = torch.ones(1, 3)
b = torch.zeros(1, 3)
b.add_(a)
b

tensor([[1., 1., 1.]])

### 自动求导机制
pytorch中非常重要的一个机制

In [10]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float, requires_grad=True)
f = x.pow(3).sum()
f.backward()
print(x.grad)

tensor([[  3.,  12.,  27.],
        [ 48.,  75., 108.]])


> 详见：
> 1. https://blog.csdn.net/landing_guy_/article/details/116724570
> 2. https://pytorch-cn.readthedocs.io/zh/latest/